describe('Booking Function', () => {
    it('Going to Login Page', () => {
        cy.visit('/')
        cy.findByText('Login').click()
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'username'}).click().type('user')
        cy.findByRole('textbox', { name: 'password'}).click().type('user')
        cy.findByRole('button', { name: 'Login'}).click()
        cy.visit('/booking/create/user')
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'date'}).click().type('2020-11-21')
        cy.findByRole('textbox', { name: 'time'}).click().type('14:00')
        cy.findByRole('textbox', { name: 'seats'}).click().type('14')
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
    let date_ob = new Date();
    let currentDay = ("0" + date_ob.getDate()).slice(-2);
    let currentMonth = ("0" + (date_ob.getMonth() + 1)).slice(-2);
    let currentYear = date_ob.getFullYear();
        cy.findByRole('textbox', { name: 'date'}).click().type(currentYear + '-' + currentMonth + '-' + currentDay)
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
        cy.findByText('Home').click()
        cy.findByText('Create Booking').click()
        cy.findByRole('textbox', { name: 'date'}).click().type('2022-11-21')
        cy.findByRole('textbox', { name: 'time'}).click().type('07:00')
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'time'}).click().type('23:00')       
        cy.findByRole('textbox', { name: 'seats'}).click().type('14')
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
        cy.visit('/login')
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'username'}).click().type('user')
        cy.findByRole('textbox', { name: 'password'}).click().type('user')
        cy.findByRole('button', { name: 'Login'}).click()
        cy.findByText('Create Booking').click()
        cy.findByRole('textbox', { name: 'date'}).click().type('2022-11-21')
        cy.findByRole('textbox', { name: 'time'}).click().type('11:00')     
        cy.findByRole('textbox', { name: 'seats'}).click().type('151')
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
        cy.visit('/login')
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'username'}).click().type('user')
        cy.findByRole('textbox', { name: 'password'}).click().type('user')
        cy.findByRole('button', { name: 'Login'}).click()
        cy.findByText('Create Booking').click()
        cy.findByRole('textbox', { name: 'date'}).click().type('2021-11-21')
        cy.findByRole('textbox', { name: 'time'}).click().type('14:00')    
        cy.findByRole('textbox', { name: 'seats'}).click().type('14')
        cy.get('select').select('10$OFF')
        cy.findByText('Chicken Caesar Salad, $20').click()
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'quantity'}).click().type('2')
        cy.findByRole('button', { name: 'Add Item'}).click()
        cy.findByText('Charcuterie Board, $30').click()
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'quantity'}).click().type('4')
        cy.findByRole('button', { name: 'Add Item'}).click()
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
        cy.visit('/login')
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'username'}).click().type('user')
        cy.findByRole('textbox', { name: 'password'}).click().type('user')
        cy.findByRole('button', { name: 'Login'}).click()
        cy.findByText('Create Booking').click()
        cy.findByRole('textbox', { name: 'date'}).click().type('2021-11-21')
        cy.findByRole('textbox', { name: 'time'}).click().type('17:00')    
        cy.findByRole('textbox', { name: 'seats'}).click().type('14')
        cy.get('select').select('50%OFF')
        cy.findByText('Beef Burger, $20').click()
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'quantity'}).click().type('2')
        cy.findByRole('button', { name: 'Add Item'}).click()
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
        cy.visit('/login')
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'username'}).click().type('user')
        cy.findByRole('textbox', { name: 'password'}).click().type('user')
        cy.findByRole('button', { name: 'Login'}).click()
        cy.findByText('Create Booking').click()
        cy.findByRole('textbox', { name: 'time'}).click().type('14:00')    
        cy.findByText('Charcuterie Board, $30').click()
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'quantity'}).click().type('4')
        cy.findByRole('button', { name: 'Add Item'}).click()
        cy.findByText('Charcuterie Board, qty:4, $120').click()
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
        cy.visit('/login')
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'username'}).click().type('user')
        cy.findByRole('textbox', { name: 'password'}).click().type('user')
        cy.findByRole('button', { name: 'Login'}).click()
        cy.findByText('Create Booking').click()
        cy.findByRole('textbox', { name: 'date'}).click().type('2021-11-21')
        cy.findByRole('textbox', { name: 'time'}).click().type('14:00')    
        cy.findByRole('textbox', { name: 'seats'}).click().type('14')
        cy.findByText('Chicken Caesar Salad, $20').click()
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'quantity'}).click().type('2')
        cy.findByRole('button', { name: 'Add Item'}).click()
        cy.get('select').select('10$OFF')
        cy.wait(500)
        cy.get('select').select('50%OFF')
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
        cy.visit('/login')
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'username'}).click().type('user')
        cy.findByRole('textbox', { name: 'password'}).click().type('user')
        cy.findByRole('button', { name: 'Login'}).click()
        cy.findByText('Create Booking').click()
        cy.findByRole('textbox', { name: 'date'}).click().type('2021-11-21')
        cy.findByRole('textbox', { name: 'time'}).click().type('14:00')    
        cy.findByRole('textbox', { name: 'seats'}).click().type('14')
        cy.findByText('Chicken Caesar Salad, $20').click()
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'quantity'}).click().type('2')
        cy.findByRole('button', { name: 'Add Item'}).click()
        cy.findByText('Charcuterie Board, $30').click()
        cy.wait(3000)
        cy.findByRole('textbox', { name: 'quantity'}).click().type('4')
        cy.findByRole('button', { name: 'Add Item'}).click()
        cy.findByRole('button', { name: 'Submit'}).click()
        cy.wait(3000)
    })
})