name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend_test_build:
    runs-on: ubuntu-latest
    name: Build Frontend (E2E tests)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Build Test Frontend
        working-directory: ./
        run: |
          npm install
          node server.js
  e2e_tests:
    name: E2E Tests
    needs: [frontend_test_build]
    runs-on: ubuntu-latest
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: cypress/included:3.8.3
    strategy:
      fail-fast: false
      matrix:
        index: [0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
      - name: Install MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo apt-get install -y mongodb-org=3.6.14 mongodb-org-server=3.6.14 mongodb-org-shell=3.6.14 mongodb-org-mongos=3.6.14 mongodb-org-tools=3.6.14
      - name: Start MongoDB
        run: sudo systemctl start mongod
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install frontend dependencies (Cypress)
        run: npm install
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: |
            node server.js
            npm start
            npm run cypress