name: Cypress Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Starting Backend
        uses: actions/setup-node@v1
        env:
          working-directory: ./
          build: node server.js
          run: npm run cypress
      - name: Cypress tests
        uses: actions/checkout@v2
        env:
          working-directory: ./cypress/integration/tests
          run: npm run cypress
          browser: chrome
          spec: 'signup&login.spec.js'
      # - name: Setup Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '12'
      # - run: node server.js
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress run
      #   uses: actions/checkout@v2
      #   with:
      #     browser: chrome
      #     start: npm run cypress
          
    #       build:

    # runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x]

    # steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Set up Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}

    # - name: Install dependencies
    #   run: npm install

    # - name: Run the tests and generate coverage report
    #   run: npm test -- --coverage

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v2.0.3
    #   with:
    #     token: ${{ secrets.3474bc51-662d-4782-9b58-095f2b4c2862 }}

    # - name: Build
    #   run: npm run build

    # - name: Deploy
    #   run: |
    #     git config --global user.name $user_name
    #     git config --global user.email $user_email
    #     git remote set-url origin https://${github_token}@github.com/${repository}
    #     npm run deploy
    #   env:
    #     user_name: 'github-actions[bot]'
    #     user_email: 'github-actions[bot]@users.noreply.github.com'
    #     github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
    #     repository: ${{ github.repository }}
      
